---
# tasks file for hampusstrom.raspberrypi

- name: Install Log2RAM.
  ansible.builtin.include_tasks:
    file: log2ram.yml
  when: rpi_log2ram_enabled

- name: Disable bluetooth.
  ansible.builtin.include_tasks:
    file: disable-bluetooth.yml
  when: rpi_disable_bluetooth
