---
# handlers file for hampusstrom.raspberrypi

- name: reboot host
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: restart log2ram
  ansible.builtin.systemd:
    name: log2ram
    state: restarted
